name: zCrates
author: Traqueur_
main: fr.traqueur.crates.zCrates
website: https://groupez.dev
version: ${version}
api-version: 1.21
softdepend:
  - MythicMobs
  - ModelEngine
  - ItemsAdder
  - Nexo
  - Oraxen
  - PlaceholderAPI
  - zItems
libraries:
  - net.kyori:adventure-api:4.18.0
  - net.kyori:adventure-text-minimessage:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4
  - org.mozilla:rhino:1.7.14
  - org.reflections:reflections:0.10.2